name: Auto Tech Post

on:
  schedule:
    - cron: '30 4 * * *'   # 9:30 AM IST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Start app (short run)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: python app.py
