name: GitHub-only Auto Poster

on:
  schedule:
    - cron: '30 4 * * *'   # 9:30 AM IST (cron uses UTC)
  workflow_dispatch:

permissions:
  contents: write   # needed so the job can commit the image back to the repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # needed for git push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "httpx==0.27.2" \
                      "openai==1.51.2" \
                      "requests==2.32.3" \
                      "pillow==10.4.0"

      - name: Run poster
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
