name: GitHub-only Auto Poster

on:
  schedule:
    - cron: '30 4 * * *'   # 9:30 AM IST (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "httpx==0.27.2" "openai==1.51.2" "requests==2.32.3" "pillow==10.4.0"

      - name: Run poster
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: python scripts/poster.py
