name: GitHub-only Auto Poster

on:
  schedule:
    - cron: '30 4 * * *'   # 9:30 AM IST (cron is UTC)
  workflow_dispatch:

permissions:
  contents: write   # needed to commit images to the repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Run poster
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # auto-provided
        run: python scripts/poster.py
